$ANSIBLE_VAULT;1.1;AES256
33626464333465383835616333353534633438373737333737623764326535333462303962643035
6639656366323930303633646162306461393234303566320a346366306631636365336438643263
64633734376432386537666262323664316331653366636437366136323739373637623130646264
6133623965333739300a623964326336646238656334303638393233366264356661356364376661
61343538666234323438326630663562333535396633646262663333633837313032623434326165
37623738306139343031313937636362396232353362613161353231383461336137663137393464
31376362326437643566363936373332326430643236353238623934616239323536343563323533
38393439393634396161366334373665393838663036663533373432313138373831383461306661
33393935623462626532383034656438616464633262613933633332633334656533
