$ANSIBLE_VAULT;1.1;AES256
39303437316264633833316237376434653137396531626639353766346163323836626430633432
3664336264653630633530383630636636383035333761640a373763393634616664353762383266
38646137663532626233623066396136643063373038306136376333633266353232613131626662
3737333034643030330a663037373461626130333938353633323130383936646530666638616332
66333331366562316230373330343536303033356635663964646566633439653963366536373139
32303938613232313838333039386431623865623339313562303339656135643330626532643862
61363131363236393064653635353866653536353838343134666535633030653039363565383738
33383363363436663733346633303130653564303666306662326338353066656339343265383031
35633633653132646537353732303736613530356366396237323432306435323730386233383962
64346430653739343539616166366164326231353439383834373866663466353365363562343633
36313531353639363264323562643433643739333535323861356635636532363565386166373766
39346664616536373663616436353765643236666335383464616137356633323535366363303763
63306539353565633863666561636563636238663035313166333633616263386165643838653164
61633930333563303337396563643862353164356430666434383630393362613565636461336466
63653939366131333762663734393665646438666538323865616231656363653463323431336639
37626436646538613666303130613363623362653836613063666165656164316239613531666133
61323138386232333266353539316639353961633134343133363630613731393435366363633135
64333861303830313561336465343665616464313233613432363063666261653930363535363533
31663937653230373133326337336138323665616165336539323133396432633861323236653763
66653930633335303839643432653664396665356131316137613434303234313865313561333365
3862
