$ANSIBLE_VAULT;1.1;AES256
33336433636139313330356261626131313236616534633766383463313231333465646562386232
3731303632343463383535666361343031316161656439610a623662646237386366373431316365
36356163306638616333353334373237613961363131323562376138353630643433363837633832
3030656133613531300a613634653832333430323537386235613861353165336563333930663434
65636539313430356531333339396638363062363535343439303962373563306636653064323439
30633164373236353236653538336133633933653533643033636437383038613436663862366264
64333161336533313335366433343631383031373037363637623137326238313436663461356264
39613665326537323262333738386266396430336265386632343034306339663533626238633764
64393438396234396638643662333236363238663632623233633062666238353363656436633733
36393131616362393534643034313038343830343133313166663834653364653234633961613662
63386335626364613134343535356239363834333436396136643762393864353133616637373533
66346165623330653166653834383834393465353634313266363934346262393738313533393565
34373566666164653163633432393235306630326331643363663331376130336636313562313333
63643836353462333532316636393737633830643430353465303266356466306638376537333839
633365663436363064333766386334363934
