$ANSIBLE_VAULT;1.1;AES256
65646466626534333935663530656432666433623264336437323635313334656630663732303164
6361303364303266303061323336333238386435353339350a313764366263376163616661363736
62646131336431616535346665643635633036393466653536363931373065393230623138323838
3039666434663439320a653935326134633663613439336635626262373634663261616633313364
61636332336533633165306138656336363366386561376162336262623666633164396333383736
39663937346361336339336639313239623462363962646638653966353035653966366633383938
35333630316235343037326261373765643135326561356337313833626530613135346536633535
66353261383332313338313033346336383431316664336561663331643532613037623634323834
36373163333366653962643734303131623138646264313336313530346164363363653664356231
6631643832383830376566373833303862396637616633333138
